name: CI
on:
  - push
  - pull_request

jobs:
  ci-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/setup.py'

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -e .

      - name: Run CI
        run: python scripts/ci.py
